### ISSUE TITLE
"com.google.inject.ProvisionException" when running "mvn install"

### ISSUE THREAD

**Issue by negora** [cincheo/jsweet-quickstart#1]
Hello:

I'm trying to run `mvn install` in the directory of the `jsweet-quickstart` project, but I'm getting an error during the `install` phase. The `generate-sources` phase works fine so, at first sight, this issue may seem not to be related with JSweet. However, when I take the `jsweet-maven-plugin` out of the `generate-sources` phase, the `install` phase works fine. This leads me to believe that it's an issue with JSweet or any of its dependencies.

The error returned by Maven is this:

```
Error injecting: org.apache.maven.artifact.installer.DefaultArtifactInstaller
com.google.inject.ProvisionException: Unable to provision, see the following errors:
...
```

Please, check the attached log file for the full trace of this error.

Why am I running `mvn install` instead of running `mvn generate-sources` directly? Right now I'm just testing, but my plan is to re-use one of my actual projects with other projects.

I'm using this software:

* OpenJDK 1.8.0-181 (or Oracle JDK 1.8.0-181; both have been tested)
* Maven 3.3.9

Thank you.

[maven-output.log](https://github.com/cincheo/jsweet-quickstart/files/2433606/output.log)

**Comment by lgrignon** [comment]
Could you please try with Maven 3.5 ?
Thanks

**Comment by negora** [comment]
Thank you @lgrignon . I've installed Maven 3.5.2 and JSweet works fine now ;) .
