### ISSUE TITLE
Couldn't run quickstart project

### ISSUE THREAD

**Issue by pedy711** [cincheo/jsweet-quickstart#4]
Hi, I followed the instructions, but when I execute `mvn generate-sources`, I get the following error:
` Execution generate-js of goal org.jsweet:jsweet-maven-plugin:2.3.0-SNAPSHOT:jsweet failed: An API incompatibility was encountered while executing org.jsweet:jsweet-maven-plugin:2.3.0-SNAPSHOT:jsweet: java.lang.NoSuchFieldError: CLASSPATH`

**Comment by lgrignon** [comment]
Hello. Still working for me. 
Which version of maven are you running please?

**Comment by lgrignon** [comment]
Just tested with maven 3.5 & 3.6.1, it works.
Are you sure you are using JDK 8?

**Comment by pedy711** [comment]
my Maven version is 3.6.0 and the project Java version was set to 1.8 JRE. I also downloaded OpenJDK 8 from the following link, but it still doesn't work.

https://github.com/ojdkbuild/ojdkbuild

Can you please provide me with the right OpenJDK 8 download link?

**Comment by lgrignon** [comment]
Could you please try oracle's jdk 8?

**Comment by pedy711** [comment]
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< org.jsweet:jsweet-quickstart >--------------------
[INFO] Building JSweet v2 quick start 2.3.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- jsweet-maven-plugin:2.3.0-SNAPSHOT:jsweet (generate-js) @ jsweet-quickstart ---
[INFO] maven version: 3.6.0
[INFO] JSweet transpiler version 2.3.0-SNAPSHOT (build date: 2019-05-01 10:19:57)
[INFO] dependencies=[Dependency {groupId=org.jsweet, artifactId=jsweet-core, version=6, type=jar}, Dependency {groupId=org.
jsweet.candies, artifactId=jquery, version=1.10.0-20170726, type=jar}]
[INFO] candies detection: add project dependency Dependency {groupId=org.jsweet, artifactId=jsweet-core, version=6, type=ja
r} => org.jsweet:jsweet-core:jar:6:compile
[INFO] candies detection: add project dependency Dependency {groupId=org.jsweet.candies, artifactId=jquery, version=1.10.0-
20170726, type=jar} => org.jsweet.candies:jquery:jar:1.10.0-20170726:compile
[INFO] all candies artifacts: [org.jsweet.candies:jquery:jar:1.10.0-20170726:compile (1; enabled), org.jsweet:jsweet-core:j
ar:6:compile (1; enabled)]
[INFO] candies jars: [C:\Users\pedra\.m2\repository\org\jsweet\candies\jquery\1.10.0-20170726\jquery-1.10.0-20170726.jar, C
:\Users\pedra\.m2\repository\org\jsweet\jsweet-core\6\jsweet-core-6.jar]
[INFO] classpath from maven: C:\Users\pedra\.m2\repository\org\jsweet\candies\jquery\1.10.0-20170726\jquery-1.10.0-20170726
.jar;C:\Users\pedra\.m2\repository\org\jsweet\jsweet-core\6\jsweet-core-6.jar
[INFO] jsOut: C:\Users\pedra\git\jsweet-quickstart\target\js
[INFO] bundle: null
[INFO] tsOut: C:\Users\pedra\git\jsweet-quickstart\target\ts
[INFO] tsOnly: null
[INFO] tsserver: null
[INFO] declarations: null
[INFO] ignoreDefinitions: null
[INFO] declarationOutDir: null
[INFO] candiesJsOutDir: C:\Users\pedra\git\jsweet-quickstart\webapp
[INFO] ecmaTargetVersion: ES6
[INFO] moduleKind: none
[INFO] sourceMap: null
[INFO] sourceRoot: null
[INFO] verbose: true
[INFO] veryVerbose: null
[INFO] jdkHome: C:\Program Files\Java\jdk1.8.0_211
[INFO] factoryClassName: null
[INFO] ignoredProblems: null
2019-05-04 09:26:56.056 ERROR JSweetConfig:149 - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to cl
ass java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java
.base of loader 'bootstrap')
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLCla
ssLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bo
otstrap')
        at org.jsweet.JSweetConfig.initClassPath(JSweetConfig.java:86)
        at org.jsweet.AbstractJSweetMojo.createJSweetTranspiler(AbstractJSweetMojo.java:254)
        at org.jsweet.JSweetMojo.execute(JSweetMojo.java:41)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.jav
a:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] extraSystemPath: null
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.969 s
[INFO] Finished at: 2019-05-04T09:26:56+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jsweet:jsweet-maven-plugin:2.3.0-SNAPSHOT:jsweet (generate-js) on project jsweet-quickst
art: Execution generate-js of goal org.jsweet:jsweet-maven-plugin:2.3.0-SNAPSHOT:jsweet failed: An API incompatibility was
encountered while executing org.jsweet:jsweet-maven-plugin:2.3.0-SNAPSHOT:jsweet: java.lang.ExceptionInInitializerError: nu
ll
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jsweet:jsweet-maven-plugin:2.3.0-SNAPSHOT
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/pedra/.m2/repository/org/jsweet/jsweet-maven-plugin/2.3.0-SNAPSHOT/jsweet-maven-plugin-2.3
.0-SNAPSHOT.jar
[ERROR] urls[1] = file:/C:/Users/pedra/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[2] = file:/C:/Users/pedra/.m2/repository/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar
[ERROR] urls[3] = file:/C:/Users/pedra/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.24/plexus-interpolation-1.
24.jar
[ERROR] urls[4] = file:/C:/Users/pedra/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1
.4.jar
[ERROR] urls[5] = file:/C:/Users/pedra/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[6] = file:/C:/Users/pedra/.m2/repository/org/apache/maven/maven-builder-support/3.5.3/maven-builder-support-3.
5.3.jar
[ERROR] urls[7] = file:/C:/Users/pedra/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.1.1/maven-resolver-ut
il-1.1.1.jar
[ERROR] urls[8] = file:/C:/Users/pedra/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3
.2.1.jar
[ERROR] urls[9] = file:/C:/Users/pedra/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.injec
t-0.3.3.jar
[ERROR] urls[10] = file:/C:/Users/pedra/.m2/repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar
[ERROR] urls[11] = file:/C:/Users/pedra/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[12] = file:/C:/Users/pedra/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar
[ERROR] urls[13] = file:/C:/Users/pedra/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-compon
ent-annotations-1.7.1.jar
[ERROR] urls[14] = file:/C:/Users/pedra/.m2/repository/org/jsweet/jsweet-transpiler/2.3.0-SNAPSHOT/jsweet-transpiler-2.3.0-
SNAPSHOT.jar
[ERROR] urls[15] = file:/C:/Users/pedra/.m2/repository/org/apache/commons/commons-text/1.3/commons-text-1.3.jar
[ERROR] urls[16] = file:/C:/Users/pedra/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[17] = file:/C:/Users/pedra/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ERROR] urls[18] = file:/C:/Users/pedra/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
[ERROR] urls[19] = file:/C:/Users/pedra/.m2/repository/com/martiansoftware/jsap/2.1/jsap-2.1.jar
[ERROR] urls[20] = file:/C:/Users/pedra/.m2/repository/com/google/javascript/closure-compiler/v20161201/closure-compiler-v2
0161201.jar
[ERROR] urls[21] = file:/C:/Users/pedra/.m2/repository/com/google/javascript/closure-compiler-externs/v20161201/closure-com
piler-externs-v20161201.jar
[ERROR] urls[22] = file:/C:/Users/pedra/.m2/repository/args4j/args4j/2.33/args4j-2.33.jar
[ERROR] urls[23] = file:/C:/Users/pedra/.m2/repository/com/google/protobuf/protobuf-java/3.0.2/protobuf-java-3.0.2.jar
[ERROR] urls[24] = file:/C:/Users/pedra/.m2/repository/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar
[ERROR] urls[25] = file:/C:/Users/pedra/.m2/repository/com/google/jsinterop/jsinterop-annotations/1.0.0/jsinterop-annotatio
ns-1.0.0.jar
[ERROR] urls[26] = file:/C:/Users/pedra/.m2/repository/fr/opensagres/js/ts.core/1.4.0-SNAPSHOT/ts.core-1.4.0-SNAPSHOT.jar
[ERROR] urls[27] = file:/C:/Users/pedra/.m2/repository/com/eclipsesource/minimal-json/minimal-json/0.9.4/minimal-json-0.9.4
.jar
[ERROR] urls[28] = file:/C:/Users/pedra/.m2/repository/org/tukaani/xz/1.8/xz-1.8.jar
[ERROR] urls[29] = file:/C:/Users/pedra/.m2/repository/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : JSweet is currently only supported for JDK8, please use JDK 8.
[ERROR] Please see this issue which asks for Java>8 support: https://github.com/cincheo/jsweet/issues/519
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by pedy711** [comment]
java -version:
`java version "1.8.0_211"                                                                                                Java(TM) SE Runtime Environment (build 1.8.0_211-b12)                                                                   Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)   `

**Comment by pedy711** [comment]
I restarted Eclipse and it took on the changes with Java 8 and it works now with JDK 8 from Oracle. Thanks

**Comment by lgrignon** [comment]
You are welcome. Enjoy ;)
