### ISSUE TITLE
Connection reset when downloading

### ISSUE THREAD

**Issue by xwb1989** [cincheo/jsweet-quickstart#6]
Hi, I was trying this quickstart project and got errors like below:

`[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JSweet quick start 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: http://repository.jsweet.org/artifactory/plugins-release-local/org/jsweet/jsweet-maven-plugin/1.1.1/jsweet-maven-plugin-1.1.1.pom
Sep 19, 2016 4:47:53 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://repository.jsweet.org:80: Connection reset
Sep 19, 2016 4:47:53 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://repository.jsweet.org:80`

I'm using Java 1.8 and mvn 3.3.9 and the network was fine.

**Comment by lgrignon** [comment]
Hello, there was an issue with the JSweet repository, indeed. It should be ok by now.

**Comment by xwb1989** [comment]
It's working now. Thanks.

**Comment by lgrignon** [comment]
@xwb1989 could you please close issue? I am not under Cincheo, thus cant close related issues.
