### ISSUE TITLE
JSweet problem in parsing JS for big projects.

### ISSUE THREAD

**Issue by frankcapodanno** [cincheo/jsweet-quickstart#8]
Hi,

I have a problem when I try to parse a big project from ts to js with Jsweet. It seems that there is a limit in the command when many ts were generated.  (Plugin with transpiler version 2.3.8) : 

TypeScript2JavaScriptWithTscTranspiler:94 - command line is too long.

Maybe  could be an idea when a lot of files from ts to js to parse to divide in many calls. 
Is this Problem noticed ?

**Comment by renaudpawlak** [comment]
Thank you for reporting, but that would be better to report in https://github.com/cincheo/jsweet
Could you tell on which OS you are running JSweet?

**Comment by frankcapodanno** [comment]
I close here the issue and I report in https://github.com/cincheo/jsweet . Many thanks!
